//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_5_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Firsrt_Name { get; set; }
        public string LastName { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Job_Title { get; set; }
        public string Gender { get; set; }
        public string Image { get; set; }
        public string CV { get; set; }
    }
}
