//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Majoer
    {
        public int id { get; set; }
        public string Major { get; set; }
        public Nullable<int> FaculityId { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
